name: eShopOnWeb Rich Code Navigation

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release

    - uses: microsoft/RichCodeNavIndexer@v0.1
      with:
        repo-token: ${{ github.token }}